GoSecure/malboxes

TODO.adoc
config-example.js
docs/Autounattend-fixing.adoc
malboxes/installconfig/windows10/Autounattend.xml
malboxes/installconfig/windows10_64/Autounattend.xml
malboxes/installconfig/windows7/Autounattend.xml
malboxes/installconfig/windows_7x64/Autounattend.xml
malboxes/malboxes.py
malboxes/profiles/snippets/builder_virtualbox_windows.json
malboxes/profiles/snippets/postprocessor_vagrant.json
malboxes/profiles/snippets/provision_powershell.json
malboxes/profiles/win10_32_analyst.json
malboxes/profiles/win10_64_analyst.json
malboxes/profiles/win7_32_analyst.json
malboxes/scripts/windows/disable_auto-updates.ps1
malboxes/scripts/windows/disable_defender.ps1
malboxes/scripts/windows/installtools.ps1
malboxes/vagrantfiles/box_win.rb

Added enough features to support the blog post I want to do. This will probably be what version 0.2.0 will look like.

Malware Analyst Use Case

---

malboxes/malboxes.py

This is done via injecting `PACKER_LOG=1` environment variable. I needed to add optional environment alteration in `run_foreground()`.
This would have made troubleshooting #19 simpler so I added it.

Packer debugging with --debug

---

docs/windows-10-tips.adoc
malboxes/installconfig/windows10/Autounattend.xml
malboxes/profiles/win10_32_analyst.json
malboxes/profiles/win10_64_analyst.json

Worked out-of-the-box for `win10_32_analyst` profile but doesn't work with `win10_64_analyst` for a reason I don't understand yet:
```
==> virtualbox-iso: Connected to WinRM!
==> virtualbox-iso: Uploading VirtualBox version info (5.1.10)
==> virtualbox-iso: Unregistering and deleting virtual machine...
==> virtualbox-iso: Deleting output directory...
Build 'virtualbox-iso' errored: Error uploading VirtualBox version: Error uploading file to $env:TEMP\winrmcp-6d14ac69-538e-47bf-4c58-76751357173b.tmp: Couldn't create shell: unknown error Post http://127.0.0.1:3674/wsman: EOF
```
I'll try to figure this out but published the branch so others can try too.

Windows 10 ISOs updated to Win10 Anniversary Edition

---

CHANGELOG.adoc
malboxes/scripts/windows/vmtools.ps1

Supports both 5.1.12 and previous certificate names by testing for the file existence.
Fixes #24

VirtualBox Guest Additions: Support for the new certificate name

---

malboxes/malboxes.py

This eases further investigation on what went wrong. Otherwise, the VM is destroyed by packer.
Worked better than #36 and is less maintenance than duplicating all profiles.

packer: add -on-error=abort when running malboxes in debug mode (#35)

---

docs/devel.adoc
malboxes/installconfig/windows7/Autounattend.xml
malboxes/installconfig/windows7/enablewinrm.ps1
malboxes/malboxes.py
malboxes/profiles/win7_32_analyst.json
malboxes/scripts/windows/fixnetworks.ps1

* New PowerShell script to set the NetworkLocation on installation. Every interface will be set to "private" which enables WinRM to run (otherwise WinRM config fails). Run as a FirstLogin script right before enabling WinRM. Fixes #33.
* Doc: Added some helpful hints to debug problems with `Autounattend.xml` FirstLogin scripts
* Doc: Added a note that `--debug` leave VMs running

Bugfix windows7 network profile

---

malboxes/installconfig/windows7/enablewinrm.ps1

Chocolatey on Windows 7 pulled in .Net 4.0 and it was unable to install due to memory limits for scripts.
Such a small fix for such a long investigation...

bugfix: Increasing WinRM memory limit for .Net 4.0 install (fixes #31)

---

malboxes/templates/snippets/provision_powershell.json
malboxes/templates/snippets/provision_powershell_win7.json

Sometimes, chocolatey decides to ignore the proxy settings,
The best way is to force it is through `choco config`
$ choco config set proxy proxy_address:3128

Force Chocolatey to use the proxy settings

---

malboxes/malboxes.py
malboxes/profile-example.js
malboxes/templates/win10_32_analyst.json
malboxes/templates/win10_64_analyst.json
malboxes/templates/win7_32_analyst.json
malboxes/templates/win7_64_analyst.json

I made the packer provisioning area customizable using the profile.
I added a packer section:
```
"packer": {
"_comment": "See https://www.packer.io/docs/templates/provisioners.html for syntax"
"provisioners": [
{
"type": "powershell",
"inline": ["dir c:\\"]
}
]
}
```
Which is copied at the end of the packer.json templates.
It allows users to add custom powershell commands (or even scripts) directly.
We use this to push custom packages (using a custom repository) using chocolatey.

Added support for defining custom provisioners in profile

---

requirements.txt

The `tojson` feature needs Jinja at least 2.9 (Should fix #80)

Fix Jinja2 version requirements

---

malboxes/installconfig/windows7/Autounattend.xml
malboxes/installconfig/windows7_64/Autounattend.xml
malboxes/scripts/windows/refresh-proxy.ps1
malboxes/templates/snippets/provision_powershell.json
malboxes/templates/snippets/provision_powershell_win7.json
malboxes/templates/win7_32_analyst.json
malboxes/templates/win7_64_analyst.json

Windows7 supports proxy configuration through `Autounattend.xml`
Unattended install sets everything needed to have a system-wide proxy
configuration.
The problem seems to be that it fails to notify `wininet` subsystem
(sometimes or always, it depends, I don't really know why/how exactly)
Anyways, this patch allow chocolatey to work **reliably** behind a proxy

Workaround for proxy support in Windows 7

---

malboxes/malboxes.py

This fixes allow configure installed packages via registry mod

Fixes in Package Mod

---

malboxes/malboxes.py

The fix to #87 . I deleted the if clause so that, if no profile is specified in the config, the `profile-example.js` is used.

Fixed default profile use.

---

malboxes/config-example.js

Process Hacker breaks install on win7_64_analyst, therefore should be removed from the default install IMO for the moment.

Removed processhacker in default install because it fails on win7_64

---

.travis.yml

Apparently Travis still doesn't support 3.7 so we are going to wait for that.

Goodbye Python 3.3. Hello 3.5 and 3.6!

---

malboxes/malboxes.py

This PR checks for the value of `PACKER_CACHE_DIR` first, and then defaults to `DIRS.user_cache_dir`.
Solves https://github.com/GoSecure/malboxes/issues/99
You can review it, i'm testing it right now.

use PACKER_CACHE_DIR env var if already set

---

malboxes/malboxes.py

Dumping the whole packer config when the debug flag is passed.
Supersedes PR #75.

Dump packer temporary config file with -d

---

Jenkinsfile
tests/smoke/Dockerfile
tests/smoke/build-all-templates.sh
tests/smoke/config.js

Will allow us to catch errors sooner. Branch to build is flexible: configured inside Jenkins itself.

Jenkins pipeline for automated VM builds of all templates

---

malboxes/templates/snippets/provision_powershell.json
malboxes/templates/snippets/provision_powershell_win7.json

They happen way too often and break entire builds. I think we can tolerate them for now.

bugfix: Tolerate 404 errors on chocolatey installs

---

Jenkinsfile
tests/smoke/Dockerfile
tests/smoke/config.js

- Worked around the Windows 7 build problem, I think it has to do with duration of the build so I streamlined it by removing chocolatey package from smoke tests. Long term goal is to use vagrant for provisioning anyway.
- Building using latest VirtualBox directly from upstream
- New `Clean` step that removes the large vagrant box files on successful builds (was generating a lot of stress for our backups)
Such a small diff for the last 19 days I spend trying to get Windows 7 builds to work...

Travis CI successfully builds Windows 7 and other improvements

---

CHANGELOG.adoc
malboxes/config-example.js
tests/smoke/config.js

Malboxes doesn't build with the default configs, so I removed the package causing problem. It still exists on Chocolatey but has been flagged by VT.

Removed APM from default chocolatey packages

---

CHANGELOG.adoc
TODO.adoc
malboxes/scripts/windows/disable_defender.ps1

From the TODO list.
Values where extracted from the following documentations:
SubmitSamplesConsent: https://docs.microsoft.com/en-us/powershell/module/defender/set-mppreference?view=win10-ps
SpynetReporting: https://getadmx.com/?Category=Windows_7_2008R2&Policy=Microsoft.Policies.WindowsDefender::SpyNetReporting

Disabled cloud protection and automatic sample submission on Windows 10

---

CHANGELOG.adoc
tests/smoke/build-all-templates.sh

Will enable building branches and PRs in Jenkins for smoke testing

CI: Install malboxes from local repository instead of upstream

---

CHANGELOG.adoc
tests/smoke/build-all-templates.sh

Otherwise python or other low-level errors don't get logged in Jenkins

CI: checking `malboxes list` return code

---

README.adoc

The readme currently only specifies the packages for Fedora and Debian. Adding ArchLinux.
The packer-io package was renamed to packer: https://www.archlinux.org/packages/community/x86_64/packer/

Added pacman command line for ArchLinux requirements

---

README.adoc

I added install notes for Ubuntu, specifically so that people do not install vagrant using the package manager. It causes issues when running malboxes.

Ubuntu requirements and detailed vagrant install

---

.travis.yml

Python 3.7 has been released in June 2018 and it is expected that security updates until approximately June 2023.
Python 3.8 has been released in October 2019 and it is expected that security updates until approximately October 2024.
See [PEP 537 -- Python 3.7 Release Schedule](https://www.python.org/dev/peps/pep-0537/) and [PEP 569 -- Python 3.8 Release Schedule ](https://www.python.org/dev/peps/pep-0569/).

Adding Python 3.7 and 3.8 to CI
